version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    reviewers:
      - "blowdart"    

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    reviewers:
      - "blowdart"
   