version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  cooldown:
    default-days: 7
  groups:
    TestSdk:
      patterns:
        - Microsoft.NET.Test.Sdk
        - Microsoft.CodeCoverage

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  cooldown:
    default-days: 7
  groups:
    github/codeql-action:
      patterns:
        - github/codeql-action/analyze
        - github/codeql-action/init
        - github/codeql-action/upload-sarif
