name: CI Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

env:
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  COVERAGE_REPORT: ${{ github.workspace}}/coveragereport

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    environment: cibuild
    permissions:
      contents: read
      issues: read
      pull-requests: write
      checks: write
    steps:
    - name: 'Harden Runner'
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - name: 'Checkout'
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        persist-credentials: false
 
    - name: 'Setup .NET SDK'
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: | 
          10.0.x

    - name: 'Restore external dependencies'
      run: dotnet restore

    - name: 'Build'
      id: build
      run: dotnet build --configuration Debug --no-restore

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: build-artifacts
        path: |
          src/**/idunno.*.nupkg
          src/**/idunno.*.dll
          src/**/idunno.*.deps.json
          src/**/idunno.*.xml
        retention-days: 5

    - name: 'Test'
      id: test
      run: dotnet test --no-build --restore --collect:"XPlat Code Coverage" --logger junit --settings .runsettings

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
      if: always()
      with:
        files: "test/**/TestResults.xml"

    - name: Upload Test Artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: test-results
        path: "test/**/TestResults.xml"
        retention-days: 5

    - name: 'Generate Full Code Coverage Reports'
      uses: danielpalme/ReportGenerator-GitHub-Action@049f7ec958c672fd31d5cc1cb01622dc8d2e23ab # 5.5.10
      with:
        reports: "test/**/coverage.cobertura.xml"
        targetdir: "${{ env.COVERAGE_REPORT }}"
        reporttypes: "Cobertura,MarkdownSummaryGithub" 
        verbosity: "Info" 
        title: "Code Coverage" 
        tag: "${{ github.run_number }}_${{ github.run_id }}"
        toolpath: "reportgeneratortool"
        license: ${{ secrets.REPORT_GENERATOR_LICENSE }}

    - name: Append coverage report to build summary
      shell: bash
      run: cat ${COVERAGE_REPORT}/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

    - name: Upload Code Coverage Results
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: coverage-results
        path: | 
          ${{ env.COVERAGE_REPORT }}
          test/**/coverage.cobertura.xml
        retention-days: 5
