name: Release Build, Test, Sign, Publish
on:
  workflow_dispatch:
    inputs:
      perform_sign:
        description: 'Sign'
        type: boolean
        required: true
        default: true
      perform_publish:
        description: 'Publish Release'
        type: boolean
        required: true
        default: true

env:
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  OUTPUT_DIRECTORY: ${{ github.workspace}}/nupkgs

permissions:
  contents: read

jobs:
  build:
    permissions:
      attestations: write
      contents: read
      id-token: write

    name: Build Rlease
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - name: 'Checkout repository'
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        persist-credentials: false
 
    - name: 'Setup .NET SDK'
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        dotnet-version: | 
          10.0.x

    - name: 'Build'
      run: dotnet build --configuration Release --property:PublicRelease=true

    - name: 'Test'
      run: dotnet test --configuration Release --no-restore --no-build --property:PublicRelease=true

    - name: 'Pack release'
      run: dotnet pack --configuration Release --no-restore  --no-build --output ${OUTPUT_DIRECTORY} --property:PublicRelease=true

    - name: 'Extract SBOMs'
      shell: pwsh
      run: > 
        Get-ChildItem -Path ${env:OUTPUT_DIRECTORY} -Filter *.nupkg -Force | ForEach-Object { 
          Expand-Archive $_.FullName "$($_.DirectoryName)/$($_.Basename)" -Force 
          Copy-Item "$($_.DirectoryName)/$($_.Basename)/_manifest/spdx_2.2/manifest.spdx.json" -Destination "${env:OUTPUT_DIRECTORY}/$($_.Basename).spdx.json"
          Copy-Item "$($_.DirectoryName)/$($_.Basename)/_manifest/spdx_2.2/manifest.spdx.json.sha256" -Destination "${env:OUTPUT_DIRECTORY}/$($_.Basename).spdx.json.sha256"
          Remove-Item "$($_.DirectoryName)/$($_.Basename)" -Force -Recurse }

    - name: Upload unsigned nupkgs to artifacts
      id: upload
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: build-artifacts
        path: ${{ env.OUTPUT_DIRECTORY }}/*
        retention-days: 7

    - name: Attest build artifacts
      uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
      with:
        subject-name: build-artifacts
        subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}


  sign:
    name: Sign
    needs: build
    runs-on: windows-latest
    if:  ${{ inputs.perform_sign }} 
    environment: release
    permissions:
      attestations: write
      contents: read
      id-token: write

    steps:
    - name: 'Setup .NET SDK'
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0

    - name: 'Install Sign CLI'
      run: dotnet tool install --tool-path ./sign --prerelease sign

    - name: 'Gather nupkgs from build output'
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: build-artifacts
        path : ${{ env.OUTPUT_DIRECTORY }}

    - name: Authenticate to Azure
      uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # 3.0.0
      with:
        allow-no-subscriptions : true
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Sign
      shell: pwsh
      run: >
        ./sign/sign code azure-key-vault *.nupkg 
        --base-directory ${env:OUTPUT_DIRECTORY} 
        --azure-key-vault-url "${{ secrets.AZURE_KEY_VAULT_URL }}" 
        --azure-key-vault-certificate "${{ secrets.AZURE_KEY_VAULT_CERTIFICATE }}"

    - name: Upload signed nupkgs to artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      id: upload
      with:
        name: signed-artifacts
        path: ${{env.OUTPUT_DIRECTORY}}/*
        retention-days: 7

    - name: Attest signed artifacts
      uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
      with:
        subject-name: signed-artifacts
        subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}

  publish:
    name: Publish
    needs: sign
    runs-on: ubuntu-latest
    if:  ${{ inputs.perform_publish }}
    environment: publish
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: 'Harden Runner'
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit

    - name: 'Setup .NET SDK'
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0

    - name: 'Gather nupkgs from signing artifacts'
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: signed-artifacts
        path : ${{ env.OUTPUT_DIRECTORY }}

    - name: Authenticate to nuget
      uses: NuGet/login@d22cc5f58ff5b88bf9bd452535b4335137e24544 # v1.0.0
      id: nugetlogin
      with:
        user: ${{secrets.NUGET_USERNAME}}

      # Use --skip-duplicate to prevent errors if a package with the same version already exists.
      # This allows a retory of a failed workflow, already published packages will be skipped without error.
    - name: Publish NuGet packages
      shell: pwsh
      run: >
        foreach($file in (Get-ChildItem "${env:OUTPUT_DIRECTORY}" -Recurse -Filter *.nupkg)) {
          dotnet nuget push $file --api-key "${{ steps.nugetlogin.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        }
